---
title: "Project_Crime"
author: "Bodi and Jinni"
date: "2023-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(reshape2)
library(rmarkdown)
library(GGally)
library(caret)
library(corrplot)
```

```{r warning=FALSE, message=FALSE}


```

Select predictors for our dataset and have one dataset that is groupped by states. 

df_com is by communities 
df_state is by states 

```{r warning=FALSE, message=FALSE}
df <- read_csv("crime.csv")
df_com <- select(df, communityName, state, ViolentCrimesPerPop, population, racepctblack, racePctWhite, racePctAsian, racePctHisp, agePct12t21, agePct12t29, agePct16t24, agePct65up, medIncome, PctPopUnderPov, PctNotHSGrad, PctUnemployed, TotalPctDiv, PctKidsBornNeverMar, RentMedian, PctForeignBorn )

df_state_dec <- df_com |> group_by(state) |> summarise(ViolentCrimesPerPop = mean(ViolentCrimesPerPop,na.rm = TRUE), population = sum(population), racepctblack = mean(racepctblack), racePctWhite = mean(racePctWhite), racePctAsian = mean(racePctAsian), racePctHisp = mean(racePctHisp), agePct12t21 = mean(agePct12t21), agePct12t29 = mean(agePct12t29), agePct16t24 = mean(agePct16t24), agePct65up = mean(agePct65up), medIncome = mean(medIncome), PctPopUnderPov = mean(PctPopUnderPov), PctNotHSGrad = mean(PctNotHSGrad), PctUnemployed = mean(PctUnemployed), TotalPctDiv = mean(TotalPctDiv), PctKidsBornNeverMar = mean(PctKidsBornNeverMar), RentMedian = mean(RentMedian), PctForeignBorn = mean(PctForeignBorn))

df_state <- df_state_dec %>%  mutate_if(is.numeric, round, digits=2)

paged_table(df_com)

```

Residuals vs Fitted Values of all predictors 
```{r warning=FALSE, message=FALSE, fig.width=8, fig.height=6 }
predictors <- df_com[,4:20]

# Title {.tabset .tabset-fade}
scatter <- function(input) {
  x <- unlist(input)
  y <- df_com$ViolentCrimesPerPop
  fit <- lm(y ~ x, data = df_com)
  plot_title <- paste("Scatter Plot of", names(input), "vs. ViolentCrimesPerPop")
  assign(paste0("plot_var", names(input)), plot(fit, 1, main = plot_title))
}

# Check for linearity with residuals vs fitted values
for (i in 1:length(predictors)) {
  scatter(predictors[, i])
}
```

```{r warning=FALSE, message=FALSE, fig.width=8, fig.height=6 }


```


Boxplots
```{r warning=FALSE, message=FALSE}

df_box <- df_com[, c("racepctblack", "racePctWhite", "racePctAsian", "racePctHisp", "medIncome")]
df_box_melt <- melt(df_box, id.vars = "medIncome", variable.name = "Race")
test <- df_box %>% gather(key = "Race", value = "Percentage", -medIncome)


ggplot(df_box_melt,aes(x = value, y = medIncome)) + geom_point() + facet_wrap(~ Race) + labs(title = "Median income vs Race Percentage") + xlab("Race Percentage") + ylab("Median Income")

df_box2 <- df_com[, c("racepctblack", "racePctWhite", "racePctAsian", "racePctHisp", "ViolentCrimesPerPop")]
df_box_melt2 <- melt(df_box2, id.vars = "ViolentCrimesPerPop", variable.name = "Race")

ggplot(df_box_melt2,aes(x = value, y = ViolentCrimesPerPop, color = Race)) + geom_point() + facet_wrap(~ Race) + labs(title = "Median income vs Race Percentage") + xlab("Race Percentage") + ylab("Median Income")


#Graph

ggplot(df_box_melt2,aes(x =value  , y = ViolentCrimesPerPop , color = Race)) + geom_point() + geom_smooth(method = "lm", color = "black", size = 0.5, alpha = 0.5) +  facet_wrap(~ Race) + labs(title = "ViolentCrimesPerPop vs Race Percentage") + ylab("ViolentCrimesPerPop") + xlab("Race Percentage") + theme(legend.position = "none")

#Graph
ggplot(df_com, aes(y =ViolentCrimesPerPop, x = medIncome)) + geom_point() + geom_smooth() + labs(title = "Median Income vs Violent Crimes per 100K people")

```

```{r warning=FALSE, message=FALSE}
R = select(df_com, -c(state,communityName)) %>% 
cor(use = "pairwise.complete.obs")
corrplot(R,method="color", addCoef.col = "black",
  order = "AOE", number.cex = 0.5, tl.cex = 0.6, tl.col = "black")

```

Histogram graph of ViolentCrimesPerPop in percentages
```{r warning=FALSE, message=FALSE}

ggplot(df_com, aes(x = ViolentCrimesPerPop)) +
  geom_histogram(binwidth = 40,color = "white", fill = "blue") +
  labs(x = "Violent Crimes per 100,000 People", y = "Frequency", title = "Frequency of Crime cases for all communities")
```

```{r warning=FALSE, message=FALSE}


```
