---
title: "R_Project"
author: "Bodi and Jinni"
date: "2023-03-09"
output: html_document
---
```{r message=FALSE,warning=FALSE}


```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries
```{r message=FALSE,warning=FALSE}
library(tidyverse)
library(ggplot2)
library(gganimate)
library(dplyr)
```

```{r message=FALSE,warning=FALSE}




```

Load dataset
```{r message=FALSE,warning=FALSE}
inmi <- read_csv2("inmi.csv") # Migrants from outside of Spain
crime <- read_csv("crime.csv") # Crime rate 
crime <- crime[-c(20,21,22,23),]
uploy <- read.delim2("tasaparo.csv", fileEncoding="latin1") # Tasa paro
uploy <- uploy[,c(2,4,5)] 
renta <- read.delim2("renta.csv", fileEncoding="latin1")
renta <- renta[,c(1,3,4)]
renta$Total <- as.numeric(renta$Total)*1000 # Easy change the decimal symbol. 
pop <- read.delim2("pop.csv", fileEncoding="latin1", dec = ",")
pop <- pop[,c(1,3,4)]

pop$Total <- gsub("[.]", "", pop$Total) #Remove "." to convert the variable to numeric. 
pop$Total <- as.numeric(pop$Total)

names(uploy)[1] <- "AR"
names(uploy)[2] <- "Year"
names(renta)[1] <- "AR"
names(renta)[2] <- "Year"
names(renta)[3] <- "Renta"
names(inmi)[1] <- "AR"
names(inmi)[2] <- "BirthCountry"
names(inmi)[3] <- "Year"
names(inmi)[4] <- "Migrants"
names(pop)[1] <- "AR"
names(pop)[2] <- "Year"
names(pop)[3] <- "Pop"
```


```{r message=FALSE,warning=FALSE}
# Filter out irrelevant/repeated info 
# Select continent index - merge all indexes - delete irrelevant observations

b <- which(inmi$BirthCountry == "Sudamérica")
c <- which(inmi$BirthCountry == "África")
d <- which(inmi$BirthCountry == "Centro América y Caribe")
e <- which(inmi$BirthCountry == "Asia")
f <- which(inmi$BirthCountry == "América del Norte")
g <- which(inmi$BirthCountry == "UE28 sin España")
h <- which(inmi$BirthCountry == "España")
i <- which(inmi$BirthCountry == "Oceanía")
new <- c(b,c,d,e,f,g,h,i) # Select indices of relevant observations/continents
inmi_select <- inmi[c(new),] 
a <- which(inmi_select$AR == "Total Nacional")
inmi1 <- inmi_select[-c(a),] # Remove Total Nacional

# Sum UE28 and Spanish migrants together as Europe category. 
inmi1$BirthCountry[inmi1$BirthCountry == "UE28 sin España"] <- "Europe"
inmi1$BirthCountry[inmi1$BirthCountry == "España"] <- "Europe"
inmi2 <- inmi1 |> group_by(AR,Year,BirthCountry) |> summarise(Migrants = sum(Migrants, na.rm = TRUE)) 

## inmi2 has the migrants across continents and year. 

# Removing years for which we don't have common data
remov <- c(which(inmi2$Year == 2008),which(inmi2$Year == 2009)) 
removidx <- unique(remov)
inmi2 <- inmi2[-c(removidx),]
inmi2$AR <- substring(inmi2$AR,4) 

#Remove numbers from AR names 
uploy$Year <- substring(uploy$Year,1,4)
uploy$AR <- substring(uploy$AR,4)
renta$AR <- substring(renta$AR,4)
pop$AR <- substring(pop$AR,4)

# Convert crime dataset to a compatible format to merge it later. 
pivot <- pivot_longer(crime,2:13, names_to = "Year", values_to = "CrimeRate")
df <- merge(inmi2,pivot, by = c("AR","Year"))  # Migrants dataframe with crime rates. 

# Converting to annual Paro data. 
uploy_annual <- uploy %>%  group_by(AR,Year) %>%  summarise(Paro = mean(Total, na.rm = TRUE))

df_add_paro <- merge(df,uploy_annual, by = c("AR","Year")) # Migrants + Crime rates + Unemployment
df_add_renta <- merge(df_add_paro, renta, by = c("AR","Year")) # Migrants + Crime rates + Unemployment + Household income
df_final <- merge(df_add_renta, pop, by = c("AR","Year")) # Final data set so far.

df_wide <- df_final |> pivot_wider(names_from = BirthCountry, values_from = Migrants)  # Final data set with migrants and Birthcountry made wider as column variables. 

colnames(df_wide)[7:13] <- c("Migrants_Africa","Migrants_NAmerica", "Migrants_Asia","Migrants_CAmerica_Caribbean","Migrants_Europe","Migrants_Oceania", "Migrants_SAmerica")

df_wide_share <- transform(df_wide, Migrants_Africa = Migrants_Africa*100/Pop, Migrants_Asia = Migrants_Asia*100/Pop,Migrants_NAmerica = Migrants_NAmerica*100/Pop, Migrants_CAmerica_Caribbean = Migrants_CAmerica_Caribbean*100/Pop, Migrants_SAmerica = Migrants_SAmerica*100/Pop, Migrants_Europe = Migrants_Europe*100/Pop, Migrants_Oceania = Migrants_Oceania*100/Pop)
                           
                      
  
  
  
```



We save some unused commands here. 
```{r message=FALSE,warning=FALSE}



df_group <- df_final %>% group_by(AR,Year,BirthCountry) %>% summarise(Migrants = sum(Migrants,na.rm = TRUE), CrimeRate = mean(CrimeRate, na.rm = TRUE)) # Groupped by AR and year to have a clear view of data without giving importance to BirthCountry. 

a <- which(inmi$AR == "Total Nacional")
b <- which(inmi$BirthCountry == "Total")
c <- which(inmi$BirthCountry == "UE27_2020 sin España")
d <- which(inmi$BirthCountry == "UE28 sin España")
e <- which(inmi$BirthCountry == "Europa menos UE28")
f <- which(inmi$BirthCountry == "Europa menos UE27_2020")


```
